/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedValuateRouteImport } from './routes/_authenticated.valuate'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedNeighborhoodsRouteImport } from './routes/_authenticated.neighborhoods'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated.map'
import { Route as AuthenticatedHpiRouteImport } from './routes/_authenticated.hpi'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedPropertyIdRouteImport } from './routes/_authenticated.property.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValuateRoute = AuthenticatedValuateRouteImport.update({
  id: '/valuate',
  path: '/valuate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNeighborhoodsRoute =
  AuthenticatedNeighborhoodsRouteImport.update({
    id: '/neighborhoods',
    path: '/neighborhoods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHpiRoute = AuthenticatedHpiRouteImport.update({
  id: '/hpi',
  path: '/hpi',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertyIdRoute = AuthenticatedPropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hpi': typeof AuthenticatedHpiRoute
  '/map': typeof AuthenticatedMapRoute
  '/neighborhoods': typeof AuthenticatedNeighborhoodsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/valuate': typeof AuthenticatedValuateRoute
  '/property/$id': typeof AuthenticatedPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hpi': typeof AuthenticatedHpiRoute
  '/map': typeof AuthenticatedMapRoute
  '/neighborhoods': typeof AuthenticatedNeighborhoodsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/valuate': typeof AuthenticatedValuateRoute
  '/property/$id': typeof AuthenticatedPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hpi': typeof AuthenticatedHpiRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/neighborhoods': typeof AuthenticatedNeighborhoodsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/valuate': typeof AuthenticatedValuateRoute
  '/_authenticated/property/$id': typeof AuthenticatedPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/hpi'
    | '/map'
    | '/neighborhoods'
    | '/reports'
    | '/valuate'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/hpi'
    | '/map'
    | '/neighborhoods'
    | '/reports'
    | '/valuate'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/hpi'
    | '/_authenticated/map'
    | '/_authenticated/neighborhoods'
    | '/_authenticated/reports'
    | '/_authenticated/valuate'
    | '/_authenticated/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/valuate': {
      id: '/_authenticated/valuate'
      path: '/valuate'
      fullPath: '/valuate'
      preLoaderRoute: typeof AuthenticatedValuateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/neighborhoods': {
      id: '/_authenticated/neighborhoods'
      path: '/neighborhoods'
      fullPath: '/neighborhoods'
      preLoaderRoute: typeof AuthenticatedNeighborhoodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hpi': {
      id: '/_authenticated/hpi'
      path: '/hpi'
      fullPath: '/hpi'
      preLoaderRoute: typeof AuthenticatedHpiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/property/$id': {
      id: '/_authenticated/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof AuthenticatedPropertyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHpiRoute: typeof AuthenticatedHpiRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedNeighborhoodsRoute: typeof AuthenticatedNeighborhoodsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedValuateRoute: typeof AuthenticatedValuateRoute
  AuthenticatedPropertyIdRoute: typeof AuthenticatedPropertyIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHpiRoute: AuthenticatedHpiRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedNeighborhoodsRoute: AuthenticatedNeighborhoodsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedValuateRoute: AuthenticatedValuateRoute,
  AuthenticatedPropertyIdRoute: AuthenticatedPropertyIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
